<?php

########################################################################
# Extension Manager/Repository config file for ext: "xm_tools"
#
# Auto generated by Extension Builder 2014-05-26
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Xima Tools',
    'description' => 'Xima helper tools.',
    'category' => 'misc',
    'author' => 'Steve Lenz, Wolfram Eberius, Sebastian Gierth',
    'author_email' => 'sle@xima.de, woe@xima.de, sgi@xima.de',
    'author_company' => 'XIMA MEDIA GmbH, XIMA MEDIA GmbH, XIMA MEDIA GmbH',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 1,
    'lockType' => '',
    'version' => '0.1.0',
    'constraints' => array(
        'depends' => array(
            'extbase' => '6.2',
            'fluid' => '6.2',
            'typo3' => '6.2',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
