<?php

########################################################################
# Extension Manager/Repository config file for ext: "xm_tools"
#
# Auto generated by Extension Builder 2014-05-26
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
    'title'            => 'XIMA Tools',
    'description'      => 'TYPO3 toolbox by XIMA MEDIA GmbH',
    'category'         => 'misc',
    'author'           => 'Sebastian Gierth, Steve Lenz, Markus Hackel',
    'author_email'     => 'sgi@xima.de, sle@xima.de, mha@xima.de',
    'author_company'   => 'XIMA MEDIA GmbH',
    'shy'              => '',
    'priority'         => '',
    'module'           => '',
    'state'            => 'stable',
    'internal'         => '',
    'uploadfolder'     => '0',
    'createDirs'       => '',
    'modify_tables'    => '',
    'clearCacheOnLoad' => 1,
    'lockType'         => '',
    'version'          => '2.8.5',
    'constraints'      => array(
        'depends'   => array(
            'php'   => '5.6.0-7.1.99',
            'typo3' => '8.7.0-8.7.99',
        ),
        'conflicts' => array(),
        'suggests'  => array(),
    ),
);
